# site properties and page defaults
title: Welcome to Computer System Security Lab. @ KENTECH!
subtitle: csslab
description: This is the website of the computer system security lab. (csslab) at KENTECH.
header: images/background.jpg
footer: images/background.jpg
proofer: false
baseurl: ""
url: "https://comsyssec.github.io"

# site social media and other links
links:
  email: hwlee@kentech.ac.kr
  orcid: 0000-0001-7490-9936
  google-scholar: IKD5nZkAAAAJ
  github: comsyssec

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
